coverage:
  range: 80..100
  round: down
  precision: 1
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        threshold: 1%

comment:
  layout: "files"
  require_changes: true
