[package]
name = "bevy_landmass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
license = "MIT"
readme = "README.md"
repository = "https://github.com/andriyDev/bevy_landmass"

categories = ["game-development"]
keywords = ["navigation", "pathfinding", "avoidance", "landmass", "bevy"]

[dependencies]
bevy = {version = "0.10.1", default-features = false}
glam = "0.24.0"
landmass = "0.1.1"

[features]
mesh-utils = ["bevy/bevy_render"]
